//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Table
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<int> ProcessType { get; set; }
        public string ProcessCategoryType { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
    
        public virtual ProcessType ProcessType1 { get; set; }
    }
}
